---

- name: Show pending reboot status from fact gathering.
  debug:
    var: ansible_reboot_pending
    verbosity: 1

- name: Set reboot flag initial value to false.
  set_fact:
    do_reboot: false
  changed_when: False

- name: Show configured reboot behavior.
  debug:
    var: winreboot_reboot_behavior
    verbosity: 2

- name: Set reboot flag based on pending reboot / simulate.
  set_fact:
    do_reboot: true
  when: (ansible_reboot_pending and winreboot_reboot_behavior == 'if_required') or winreboot_reboot_behavior == 'always'
  changed_when: False

- name: Reboot status.
  debug:
    var: do_reboot
    verbosity: 2

- name: Reboot.
  win_reboot:
    connect_timeout: "{{ winreboot_connect_timeout | default(omit) }}"
    reboot_timeout: "{{ winreboot_reboot_timeout | default(omit) }}"
  check_mode: "{{ winreboot_simulate | bool | ternary('yes', 'no') }}"
  register: reboot_return
  when: do_reboot

- debug:
    var: reboot_return
    verbosity: 2
